name: Deploy

on:
  push:
    branches:
      - main  # Push to main branch
      - ci-cd/*

jobs:
  publish:
    runs-on: "ubuntu-latest"
    if: "contains(github.event.head_commit.message, '--trigger-cd') || contains(github.event.head_commit.message, 'Merge & deploy')"

    steps:
      - uses: actions/checkout@v3

      - name: Update repos list
        run: sudo apt-get update
      - name: Build images
        run: |
          docker build -t ghcr.io/seba1204/terrain7 .
      - name: Login to GitHub Packages
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ env.TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push to GitHub Packages
        id: push-to-gh-packages
        run: |
          tag=$(git rev-parse --short HEAD)
          docker tag ghcr.io/seba1204/terrain7 ghcr.io/seba1204/terrain7:$tag
          docker push ghcr.io/seba1204/terrain7:$tag
          docker push ghcr.io/seba1204/terrain7
          echo ::set-output name=tag::$tag
      
      - name: Logout
        run: |
          docker logout
      
      - name: Create commit comment
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            ## Summary
            ✅ Commit successfully deployed to GitHub packages.
            🔗 Commit reference: `${{ github.sha }}`
            📦 Deployed image tag: `${{ steps.push-to-gh-packages.outputs.tag }}`